typography_spectrum: 0.40673898509703577
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.45366490981541574
  lightness: 0.825374361127615
  saturation: 0.9874923718161881
  rhythmicContrast: 0.5945594399236143
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4484891048632562
analytics:
  google: null
  facebook: null
  twitter: null
name: Sporting Hares
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: British Excellence
description: since 2011.
purpose: []
